// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BHDHRMWebAPI.Models
{
    public partial class BhdAccount
    {
        public BhdAccount()
        {
            RefreshToken = new HashSet<RefreshToken>();
        }

        public string UserAd { get; set; }
        public string Pass { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Login { get; set; }
        public string TimeCreate { get; set; }
        public int? Roles { get; set; }
        public string Token { get; set; }
        public int? IdGroup { get; set; }
        public int? CinemaId { get; set; }
        public string UserNo { get; set; }

        public virtual BhdGroup IdGroupNavigation { get; set; }
        public virtual ICollection<RefreshToken> RefreshToken { get; set; }
    }
}