// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BHDHRMWebAPI.Models
{
    public partial class BhdGroup
    {
        public BhdGroup()
        {
            BhdAccount = new HashSet<BhdAccount>();
            BhdRoles = new HashSet<BhdRoles>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public string UserCreate { get; set; }
        public string UserEdit { get; set; }
        public string TimeModify { get; set; }
        public string TimeCreate { get; set; }

        public virtual ICollection<BhdAccount> BhdAccount { get; set; }
        public virtual ICollection<BhdRoles> BhdRoles { get; set; }
    }
}