// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using System;
using System.Data;
using System.Linq;
using BHDHRMWebAPI.Models;

namespace BHDHRMWebAPI.Models
{
    public partial class BHDHRMContext
    {

        [DbFunction("SoNgayTrongThang", "dbo")]
        public static int? SoNgayTrongThang(DateTime? myDateTime)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        protected void OnModelCreatingGeneratedFunctions(ModelBuilder modelBuilder)
        {
        }
    }
}
