// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BHDHRMWebAPI.Models
{
    public partial class BhdRoles
    {
        public int Id { get; set; }
        public int? IdFn { get; set; }
        public int? IdGr { get; set; }
        public string UserCreate { get; set; }
        public string UserEdit { get; set; }
        public DateTime? TimeModify { get; set; }
        public DateTime? TimeCreate { get; set; }
        public int? Idrap { get; set; }
        public int? Idpermit { get; set; }
        public string Idpermittype { get; set; }

        public virtual Modules IdFnNavigation { get; set; }
        public virtual BhdGroup IdGrNavigation { get; set; }
    }
}