// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BHDHRMWebAPI.Models
{
    public partial class Error
    {
        public int Id { get; set; }
        public string Text { get; set; }
        public DateTime? TimeCreate { get; set; }
    }
}