// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using BHDHRMWebAPI.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace BHDHRMWebAPI.Models
{
    public partial interface IBHDHRMContextProcedures
    {
        Task<List<prNgayCongResult>> prNgayCongAsync(int? Thang, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<pro_HR_BC_HopDongHetHanResult>> pro_HR_BC_HopDongHetHanAsync(string Rap, string Phong, string Ngay, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<pro_HR_BC_LuongResult>> pro_HR_BC_LuongAsync(string Rap, string Phong, string MaNV, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<pro_HR_BC_SinhNhatResult>> pro_HR_BC_SinhNhatAsync(string Rap, string Phong, string MaNV, string Thang, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<pro_HR_BC_TroCapResult>> pro_HR_BC_TroCapAsync(string Rap, string Phong, string MaNV, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<pro_HR_LuongPTResult>> pro_HR_LuongPTAsync(string Rap, DateTime? ngay, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<pro_Menu1Result>> pro_Menu1Async(string group, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<pro_Menu2Result>> pro_Menu2Async(string group, string Menu, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<pro_Menu3Result>> pro_Menu3Async(string group, string Menu, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
