// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BHDHRMWebAPI.Models
{
    public partial class Luongtran
    {
        public int Id { get; set; }
        public string Maluong { get; set; }
        public int? LuongBhxh { get; set; }
        public int? Luongbhtn { get; set; }
        public int? Luongbhyt { get; set; }
        public int? Muctoithieu { get; set; }
        public DateTime? Ngayhieuluc { get; set; }
        public string Ghichu { get; set; }
    }
}