// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace BHDHRMWebAPI.Models
{
    public partial class prNgayCongResult
    {
        public string CardNumber { get; set; }
        public string HoTen { get; set; }
        public int? P { get; set; }
        public int? O { get; set; }
        public int? B { get; set; }
        public int? M { get; set; }
        public int? R { get; set; }
        public int? L { get; set; }
        public int? Lo { get; set; }
        public int? OD { get; set; }
        public int? X { get; set; }
    }
}
