// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace BHDHRMWebAPI.Models
{
    public partial class pro_HR_BC_TroCapResult
    {
        public string CardNumber { get; set; }
        public string HoTen { get; set; }
        public string TenCongTy { get; set; }
        public string TenPhong { get; set; }
        public string ChucVu { get; set; }
        public int? Com { get; set; }
        public int? Xang { get; set; }
        public int? DienThoai { get; set; }
        public int? GuiXe { get; set; }
        public int? Khac { get; set; }
        public string GhiChu { get; set; }
    }
}
