// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace BHDHRMWebAPI.Models
{
    public partial class pro_HR_BC_HopDongHetHanResult
    {
        public string CardNumber { get; set; }
        public string HoTen { get; set; }
        public string ChucVu { get; set; }
        public DateTime? NgayBatDau { get; set; }
        public DateTime? NgayHetHan { get; set; }
        public string LoaiHopDong { get; set; }
        public string GhiChu { get; set; }
        public string LanTaiKy { get; set; }
    }
}
