// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace BHDHRMWebAPI.Models
{
    public partial class pro_HR_LuongPTResult
    {
        public string CardNumber { get; set; }
        public string HoTen { get; set; }
        public decimal? AMcu { get; set; }
        public decimal? PMcu { get; set; }
        public decimal? AMmoi { get; set; }
        public decimal? PMmoi { get; set; }
        public decimal? GioTraining { get; set; }
        public decimal? LuongCu { get; set; }
        public decimal? LuongMoi { get; set; }
        public decimal? LuongTraining { get; set; }
        public decimal? PhuCapKhac { get; set; }
        public decimal? ThueTNCN { get; set; }
        public decimal? TongTuong { get; set; }
        public decimal? ThucLinh { get; set; }
    }
}
