// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace BHDHRMWebAPI.Models
{
    public partial class pro_HR_BC_SinhNhatResult
    {
        public string CardNumber { get; set; }
        public string HoTen { get; set; }
        public string ChucVu { get; set; }
        public DateTime? NgaySinh { get; set; }
        public DateTime? NgayVaoCongTy { get; set; }
        public string Email { get; set; }
        public string Email2 { get; set; }
        public string TenPhong { get; set; }
    }
}
