// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BHDHRMWebAPI.Models
{
    public partial class TableTest1
    {
        public int Id { get; set; }
        public string MaNv { get; set; }
        public string Ten { get; set; }
        public string Diem { get; set; }
    }
}