// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BHDHRMWebAPI.Models
{
    public partial class Table1
    {
        public int Id { get; set; }
        public string Phone { get; set; }
        public string Emails { get; set; }
    }
}