// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BHDHRMWebAPI.Models
{
    public partial class Tb1
    {
        public int Id { get; set; }
        public string CardNumber { get; set; }
        public string HoTen { get; set; }
    }
}