// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BHDHRMWebAPI.Models
{
    public partial class TblCapbac
    {
        public int Id { get; set; }
        public string Macapbac { get; set; }
        public string Tencapbac { get; set; }
        public int? Trocap { get; set; }
        public DateTime? Ngaytao { get; set; }
        public string Nguoitao { get; set; }
        public string Ghichu { get; set; }
        public int? Tiencom { get; set; }
        public int? Xang { get; set; }
        public int? Dienthoai { get; set; }
        public int? Dilai { get; set; }
        public int? Guixe { get; set; }
    }
}