// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BHDHRMWebAPI.Models
{
    public partial class TblChamCong
    {
        public string CardNumber { get; set; }
        public DateTime Ngay { get; set; }
        public string NgayCong { get; set; }
    }
}