// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BHDHRMWebAPI.Models
{
    public partial class TblChamCongPt
    {
        public string CardNumber { get; set; }
        public DateTime Thang { get; set; }
        public decimal? Amcu { get; set; }
        public decimal? Pmcu { get; set; }
        public decimal? Ammoi { get; set; }
        public decimal? Pmmoi { get; set; }
        public decimal? GioTraining { get; set; }
        public decimal? LuongCu { get; set; }
        public decimal? LuongMoi { get; set; }
        public decimal? LuongTraining { get; set; }
        public decimal? Thuong { get; set; }
        public decimal? PhuCapKhac { get; set; }
        public decimal? ThueTncn { get; set; }
    }
}