// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BHDHRMWebAPI.Models
{
    public partial class TblChucVu
    {
        public string Id { get; set; }
        public string TenChucVu { get; set; }
        public int? UuTien { get; set; }
    }
}