// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BHDHRMWebAPI.Models
{
    public partial class TblCongTy
    {
        public int Id { get; set; }
        public string IdtapDoan { get; set; }
        public string TenCongTy { get; set; }
        public string DiaChi { get; set; }
        public string SoDt { get; set; }
        public string TinhTrang { get; set; }
        public int? AreaId { get; set; }
        public bool? HienThi { get; set; }

        public virtual Area Area { get; set; }
    }
}