// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BHDHRMWebAPI.Models
{
    public partial class TblGiaDinh
    {
        public string CardNumber { get; set; }
        public string QuanHe { get; set; }
        public string HoTen { get; set; }
        public DateTime? NgaySinh { get; set; }
        public string GioiTinh { get; set; }
        public string NguoiPhuThuoc { get; set; }
        public string MaSoThuePhuThuoc { get; set; }
        public int? TienGiamTru { get; set; }
        public string SoDt { get; set; }
        public int Id { get; set; }
    }
}