// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BHDHRMWebAPI.Models
{
    public partial class TblHopDong
    {
        public string CardNumber { get; set; }
        public string SoHopDong { get; set; }
        public string LoaiHopDong { get; set; }
        public string LanTaiKy { get; set; }
        public string NguoiKy { get; set; }
        public DateTime? NgayKy { get; set; }
        public DateTime? NgayBatDau { get; set; }
        public DateTime? NgayHetHan { get; set; }
        public int? MucLuong { get; set; }
        public string GhiChu { get; set; }
        public int Id { get; set; }
    }
}