// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BHDHRMWebAPI.Models
{
    public partial class TblKhenThuongKyLuat
    {
        public string CardNumber { get; set; }
        public DateTime? Ngay { get; set; }
        public string HinhThuc { get; set; }
        public string NoiDung { get; set; }
        public string ThoiHanApDung { get; set; }
        public string SoQd { get; set; }
        public string GhiChu { get; set; }
        public int Id { get; set; }
    }
}