// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BHDHRMWebAPI.Models
{
    public partial class TblLuongKhac
    {
        public string CardNumber { get; set; }
        public DateTime TuNgay { get; set; }
        public DateTime? DenNgay { get; set; }
        public int? HoaHong { get; set; }
        public int? ThuNhapKhac { get; set; }
        public int? SinhNhat { get; set; }
        public int? KhoanGiamTru { get; set; }
        public string GhiChu { get; set; }
        public int Id { get; set; }
        public int? Tiepkhach { get; set; }
    }
}