// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BHDHRMWebAPI.Models
{
    public partial class TblLuong
    {
        public string CardNumber { get; set; }
        public DateTime TuNgay { get; set; }
        public DateTime? DenNgay { get; set; }
        public int? LuongCb { get; set; }
        public string LyDo { get; set; }
        public int? Luongthoathuan { get; set; }
        public int Id { get; set; }
    }
}