// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BHDHRMWebAPI.Models
{
    public partial class TblLogPoint
    {
        public int Id { get; set; }
        public string Cardnumber { get; set; }
        public int? Point { get; set; }
        public DateTime? Ngaythaotac { get; set; }
        public string Nguoithaotac { get; set; }
    }
}