// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BHDHRMWebAPI.Models
{
    public partial class TblMenu
    {
        public string Id { get; set; }
        public string IdMenu { get; set; }
        public string MenuName { get; set; }
        public string IdSubMenu1 { get; set; }
        public string SubMenuName1 { get; set; }
        public string IdSubMenu2 { get; set; }
        public string SubMenuName2 { get; set; }
    }
}