// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BHDHRMWebAPI.Models
{
    public partial class TblNgayle
    {
        public int Id { get; set; }
        public string Manghi { get; set; }
        public DateTime? Ngaynghilam { get; set; }
        public string Mota { get; set; }
    }
}