// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BHDHRMWebAPI.Models
{
    public partial class TblNghiPhep
    {
        public string MaPhieu { get; set; }
        public int? MaNv { get; set; }
        public string LoaiNghi { get; set; }
        public string NoiDung { get; set; }
        public DateTime? TuNgay { get; set; }
        public DateTime? DenNgay { get; set; }
        public DateTime? NgayLamLai { get; set; }
        public string TrangThai { get; set; }
        public string MaNguoiDuyet { get; set; }
        public string EmailNguoiDuyet { get; set; }
        public string GhiChuNguoiDuyet { get; set; }
        public string TimeCreate { get; set; }
        public string TimeUpdate { get; set; }
    }
}