// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BHDHRMWebAPI.Models
{
    public partial class TblNgayNghi
    {
        public string CardNumber { get; set; }
        public int Nam { get; set; }
        public int? Phep { get; set; }
        public int? Bu { get; set; }
        public int? Le { get; set; }
    }
}