// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BHDHRMWebAPI.Models
{
    public partial class TblNhanVienImg
    {
        public int Id { get; set; }
        public int? IdNhanVien { get; set; }
        public string Avatar { get; set; }
        public string HinhCmnd { get; set; }
        public string ThoiGianTao { get; set; }
        public string LanCuoiChinhSua { get; set; }
    }
}