// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BHDHRMWebAPI.Models
{
    public partial class TblPhong
    {
        public string Id { get; set; }
        public int IdcongTy { get; set; }
        public string TenPhong { get; set; }
        public string GhiChu { get; set; }
        public virtual TblCongTy TblCongTy { get; set; }
    }
}