// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BHDHRMWebAPI.Models
{
    public partial class TblPhucLoi
    {
        public int Id { get; set; }
        public DateTime? NgayThuong { get; set; }
        public string LoaiHopDong { get; set; }
        public int? ThangLamViec { get; set; }
        public long? TienThuong { get; set; }
    }
}