// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BHDHRMWebAPI.Models
{
    public partial class TblQuaTrinhCongViecNew
    {
        public string CardNumber { get; set; }
        public DateTime? TuNgay { get; set; }
        public DateTime? DenNgay { get; set; }
        public string ChucVu { get; set; }
        public string PhongBan { get; set; }
        public string DiaDiemLv { get; set; }
        public int? LuongGross { get; set; }
        public string GhiChu { get; set; }
        public int Id { get; set; }
    }
}