// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BHDHRMWebAPI.Models
{
    public partial class TblQuaTrinhDaoTao
    {
        public string CardNumber { get; set; }
        public DateTime? Ngay { get; set; }
        public string NoiDungDt { get; set; }
        public string DiaDiem { get; set; }
        public string Kq { get; set; }
        public string ThoiGianDt { get; set; }
        public string ThoHanCamKet { get; set; }
        public string NhanXetDanhGia { get; set; }
        public string GhiChu { get; set; }
        public int Id { get; set; }
    }
}