// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BHDHRMWebAPI.Models
{
    public partial class TblQuaTrinhHocTap
    {
        public string CardNumber { get; set; }
        public DateTime? TuNgay { get; set; }
        public DateTime? DenNgay { get; set; }
        public string Truong { get; set; }
        public string TrinhDo { get; set; }
        public string ChuyenNganh { get; set; }
        public string BangTotNghiep { get; set; }
        public string LoaiTotNghiep { get; set; }
        public string GhiChu { get; set; }
        public int Id { get; set; }
    }
}