// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BHDHRMWebAPI.Models
{
    public partial class TblQuaTrinhCongTac
    {
        public string CardNumber { get; set; }
        public DateTime? TuNam { get; set; }
        public DateTime? DenNam { get; set; }
        public string TenCty { get; set; }
        public string ChucVu { get; set; }
        public string LyDoThoiViec { get; set; }
        public string GhiChu { get; set; }
        public int Id { get; set; }
    }
}