// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BHDHRMWebAPI.Models
{
    public partial class TblQuaTrinhCongViec
    {
        public string CardNumber { get; set; }
        public int Stt { get; set; }
        public DateTime? TuNgay { get; set; }
        public DateTime? DenNgay { get; set; }
        public string ChucVu { get; set; }
        public string KhenThuong { get; set; }
        public string KyLuat { get; set; }
        public string GhiChu { get; set; }
    }
}