// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BHDHRMWebAPI.Models
{
    public partial class TblScheduler
    {
        public long Id { get; set; }
        public long LocationId { get; set; }
        public long PersonId { get; set; }
        public string Note { get; set; }
        public DateTime Start { get; set; }
        public DateTime End { get; set; }
        public string Recurrence { get; set; }
        public string Color { get; set; }
        public bool? Status { get; set; }
        public string LoaiNghi { get; set; }
        public string NoiDung { get; set; }
        public string TrangThai { get; set; }
        public int? NguoiDuyet { get; set; }
        public string GhiChuNguoiDuyet { get; set; }
        public DateTime? TimeCreate { get; set; }
        public DateTime? TimeUpdate { get; set; }
        public DateTime? TimeApprove { get; set; }
    }
}