// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BHDHRMWebAPI.Models
{
    public partial class TblSubMenu
    {
        public string Id { get; set; }
        public string IdMenu { get; set; }
        public string SubMenuName { get; set; }
        public string Descriptions { get; set; }
    }
}