// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BHDHRMWebAPI.Models
{
    public partial class TblTroCap
    {
        public string CardNumber { get; set; }
        public DateTime? TuNgay { get; set; }
        public DateTime? DenNgay { get; set; }
        public int? Com { get; set; }
        public int? DienThoai { get; set; }
        public int? Xang { get; set; }
        public int? PhuongTien { get; set; }
        public int? GuiXe { get; set; }
        public int? TrachNhiem { get; set; }
        public int? Khac { get; set; }
        public string GhiChu { get; set; }
        public int Id { get; set; }
    }
}