// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BHDHRMWebAPI.Models
{
    public partial class TblTangCa
    {
        public string CardNumber { get; set; }
        public DateTime Thang { get; set; }
        public double? Giolamch { get; set; }
        public double? Giolamch22 { get; set; }
        public double? Ngaythuong { get; set; }
        public double? Ngathuong22 { get; set; }
        public double? Ngayoff { get; set; }
        public double? Ngayoff22h { get; set; }
        public double? Ngayle { get; set; }
        public double? Ngayle22 { get; set; }
        public double? Giolamch22le { get; set; }
        public double? Giolamchtv { get; set; }
        public double? Giolamch22tv { get; set; }
        public double? Ngaythuongtv { get; set; }
        public double? Ngathuong22tv { get; set; }
        public double? Ngayofftv { get; set; }
        public double? Ngayoff22htv { get; set; }
        public double? Ngayletv { get; set; }
        public double? Ngayle22tv { get; set; }
        public double? Giolamch22letv { get; set; }
    }
}