// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BHDHRMWebAPI.Models
{
    public partial class TblTrocaptrachnhiem
    {
        public int Id { get; set; }
        public string CardNumber { get; set; }
        public double? Trocaptrachnhiem { get; set; }
        public double? Trocapkhac { get; set; }
        public DateTime? Tungay { get; set; }
        public DateTime? Denngay { get; set; }
        public string Ghichu { get; set; }
    }
}