// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BHDHRMWebAPI.Models
{
    public partial class TblTaiSanCap
    {
        public string CardNumber { get; set; }
        public string TenTs { get; set; }
        public string DonViTinh { get; set; }
        public int? SoLuong { get; set; }
        public string TraTaiSan { get; set; }
        public string GhiChu { get; set; }
        public int Id { get; set; }
    }
}