// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BHDHRMWebAPI.Models
{
    public partial class TblTapDoan
    {
        public string Id { get; set; }
        public string TenTapDoan { get; set; }
        public string DiaChi { get; set; }
    }
}