// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BHDHRMWebAPI.Models
{
    public partial class TblUrl
    {
        public int Id { get; set; }
        public string Url { get; set; }
        public bool? Status { get; set; }
        public string Email { get; set; }
    }
}