// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BHDHRMWebAPI.Models
{
    public partial class Thietlapbaohiem
    {
        public int Id { get; set; }
        public DateTime? Ngayhieuluc { get; set; }
        public double? Bhxhcty { get; set; }
        public double? Bhytcty { get; set; }
        public double? Bhtncty { get; set; }
        public double? Bhxhnv { get; set; }
        public double? Bhytnv { get; set; }
        public double? Bhtnnv { get; set; }
    }
}