// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BHDHRMWebAPI.Models
{
    public partial class Thietlapthue
    {
        public int Id { get; set; }
        public string Tendinhmuc { get; set; }
        public bool? Trangthai { get; set; }
        public int? Thunhaptu { get; set; }
        public double? Thunhapden { get; set; }
        public double? Phantramnop { get; set; }
        public int? Sotien { get; set; }
        public string Mota { get; set; }
        public DateTime? Ngayhieuluc { get; set; }
    }
}